CREATE SEQUENCE primary_sequence
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS employee (
                                        id int8 generated by default as identity,
                                        date_of_birth varchar(255),
    deleted boolean not null,
    employee_id uuid,
    gender varchar(255),
    phone varchar(255),
    name_id int8,
    primary key (id)
    );

create table IF NOT EXISTS address (
                                       id int8 not null,
                                       exterior varchar(255),
    interior varchar(255),
    street varchar(255),
    city varchar(255),
    postal_code varchar(255),
    state varchar(255),
    employee_id int8,
    primary key (id)
    );

create table IF NOT EXISTS email (
                                     id int8 not null,
                                     email_address varchar(255),
    email_type varchar(255),
    email_id int8,
    primary key (id)
    );

create table IF NOT EXISTS employee_names (
                                              id int8 generated by default as identity,
                                              first varchar(255),
    last varchar(255),
    primary key (id)
    );

create table IF NOT EXISTS employee_role_and_salary (
                                                        id int8 generated by default as identity,
                                                        employee_id uuid,
                                                        end_date varchar(255),
    role varchar(255),
    salary varchar(255),
    start_date varchar(255) not null,
    primary key (id)
    );

create table IF NOT EXISTS employee_salary_and_difference_view (
                                                                   id int8 not null,
                                                                   max_salary int4 not null,
                                                                   min_salary int4 not null,
                                                                   salary_diff int4 not null,
                                                                   primary key (id)
    );

create table IF NOT EXISTS user_and_role (
                                             id int8 generated by default as identity,
                                             password varchar(255),
    role varchar(255),
    username varchar(255),
    primary key (id)
    );

INSERT INTO user_and_role (id, username, role, password) values (1, 'Test-First-Name', 'admin', 'Test-Second-Name');